dist: trusty

sudo: false

compiler:
  - gcc
  - clang

python:
  - "3.6"

install:
  - source ~/virtualenv/python3.6/bin/activate
  - pip3 install -r requirements.txt

script:
  - mkdir -p build
  - cd build
  - cmake -DHACKERRANK_FP:BOOL=OFF -DCMAKE_BUILD_TYPE=Release ..
  - make -j$(nproc)
  - make extract-testcases
  - ctest -j$(nproc) --output-on-failure
