dist: trusty

sudo: false

compiler:
  - gcc
  - clang

language:
  - python

python:
  - "3.6"

install:
  - source ~/virtualenv/python3.6/bin/activate
  - pip3 install -r requirements.txt

script:
  - mkdir -p build
  - cd build
  - cmake -DHACKERRANK_FP:BOOL=OFF -DCMAKE_BUILD_TYPE=Release ..
  - cd c
  - make -j$(nproc) VERBOSE=1
  - cd ..
  - make extract-testcases
  - cd c
  - ctest -j$(nproc) --output-on-failure
