dist: trusty
sudo: false
language: python
python:
  - "3.6"
ghc:
  - "7.8"
install:
  - pip install -r requirements.txt
script:
  - mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - ctest
