dist: trusty
sudo: false
language: python
python:
  - "3.6"
ghc:
  - "7.8"
install:
  - pip install -r requirements.txt
script:
  - nproc
  - nproc --all
  - getconf _NPROCESSORS_ONLN
  - mkdir -p build
  - cd build
  - cmake -DHACKERRANK_FP:BOOL=OFF -DCMAKE_BUILD_TYPE=Release ..
  - make -j16
  - ctest --output-on-failure
