dist: trusty
sudo: false
language: python
python:
  - "3.6"
ghc:
  - "7.8"
install:
  - pip install -r requirements.txt
script:
  - env
  - mkdir -p build
  - cd build
  - cmake -DHACKERRANK_FP:BOOL=OFF -DCMAKE_BUILD_TYPE=Release ..
  - make -j4
  - ctest -j4 -VV
  - cat python/numpy/np-linear-algebra.py.log