dist: trusty
sudo: false
compiler: clang
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - mkdir -p build
  - cd build
  - cmake -DHACKERRANK_FP:BOOL=OFF -DCMAKE_BUILD_TYPE=Release ..
  - make -j$(nproc)
  - make extract-testcases
  - ctest -j$(nproc) --output-on-failure
